version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/recipe_api/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'recipe'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
