version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/recipe_api/
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >-
      sh -c 'python manage.py makemigrations &&
      python manage.py migrate &&
      python db_uploader.py &&
      gunicorn --bind 0.0.0.0:8000 recipe_api.wsgi:application'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'admin'
      MYSQL_DATABASE: 'recipe'
      MYSQL_PASSWORD: 'password'
    ports:
      - "3307:3307"
    expose:
      - "3307"