version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/recipe_api/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'parkjh'
      MYSQL_DATABASE: 'recipe'
      MYSQL_PASSWORD: '1234'
    ports:
      - "3307:3307"
    expose:
      - "3307"
